import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { cn } from "~/lib/utils";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          GeistSans.className
        )}>{children}</body>
    </html>
  );
}
